export const LOGIN_WITH_FACEBOOK = 'auth/LOGIN_WITH_FACEBOOK';
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'auth/LOGIN_WITH_FACEBOOK_SUCCESS';
export const LOGIN_WITH_FACEBOOK_ERROR = 'auth/LOGIN_WITH_FACEBOOK_ERROR';
export const FETCH_ME = 'auth/FETCH_ME';
export const FETCH_ME_SUCCESS = 'auth/FETCH_ME_SUCCESS';
export const FETCH_ME_ERROR = 'auth/FETCH_ME_ERROR';
