export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const SUBSCRIBE = 'SUBSCRIBE';
export const SUBSCRIBE_ERROR = 'SUBSCRIBE_ERROR';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
